//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.09 at 04:52:08 PM IST 
//


package x.y.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}artref"/>
 *         &lt;element ref="{}capt"/>
 *         &lt;element ref="{}dim"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "artref",
    "capt",
    "dim"
})
@XmlRootElement(name = "art")
public class Art {

    @XmlElement(required = true)
    protected Artref artref;
    @XmlElement(required = true)
    protected Capt capt;
    @XmlElement(required = true)
    protected Dim dim;

    /**
     * Gets the value of the artref property.
     * 
     * @return
     *     possible object is
     *     {@link Artref }
     *     
     */
    public Artref getArtref() {
        return artref;
    }

    /**
     * Sets the value of the artref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Artref }
     *     
     */
    public void setArtref(Artref value) {
        this.artref = value;
    }

    /**
     * Gets the value of the capt property.
     * 
     * @return
     *     possible object is
     *     {@link Capt }
     *     
     */
    public Capt getCapt() {
        return capt;
    }

    /**
     * Sets the value of the capt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Capt }
     *     
     */
    public void setCapt(Capt value) {
        this.capt = value;
    }

    /**
     * Gets the value of the dim property.
     * 
     * @return
     *     possible object is
     *     {@link Dim }
     *     
     */
    public Dim getDim() {
        return dim;
    }

    /**
     * Sets the value of the dim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dim }
     *     
     */
    public void setDim(Dim value) {
        this.dim = value;
    }

}
