//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.09 at 04:52:08 PM IST 
//


package x.y.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{}vt" minOccurs="0"/>
 *         &lt;element ref="{}date" minOccurs="0"/>
 *         &lt;element ref="{}sl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}sense"/>
 *         &lt;element ref="{}ss" minOccurs="0"/>
 *         &lt;element ref="{}us" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vtAndDateAndSl"
})
@XmlRootElement(name = "def")
public class Def {

    @XmlElements({
        @XmlElement(name = "vt", required = true, type = Vt.class),
        @XmlElement(name = "date", required = true, type = Date.class),
        @XmlElement(name = "sl", required = true, type = Sl.class),
        @XmlElement(name = "sense", required = true, type = Sense.class),
        @XmlElement(name = "ss", required = true, type = Ss.class),
        @XmlElement(name = "us", required = true, type = Us.class)
    })
    protected List<Object> vtAndDateAndSl;

    /**
     * Gets the value of the vtAndDateAndSl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vtAndDateAndSl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVtAndDateAndSl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Vt }
     * {@link Date }
     * {@link Sl }
     * {@link Sense }
     * {@link Ss }
     * {@link Us }
     * 
     * 
     */
    public List<Object> getVtAndDateAndSl() {
        if (vtAndDateAndSl == null) {
            vtAndDateAndSl = new ArrayList<Object>();
        }
        return this.vtAndDateAndSl;
    }

}
