//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.09 at 04:52:08 PM IST 
//


package x.y.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}drp"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}pr"/>
 *           &lt;element ref="{}pr_alt" minOccurs="0"/>
 *           &lt;element ref="{}pr_ipa" minOccurs="0"/>
 *           &lt;element ref="{}pr_wod" minOccurs="0"/>
 *           &lt;element ref="{}sound" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}vr" minOccurs="0"/>
 *         &lt;element ref="{}et" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}def"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drp",
    "pr",
    "prAlt",
    "prIpa",
    "prWod",
    "sound",
    "vr",
    "et",
    "def"
})
@XmlRootElement(name = "dro")
public class Dro {

    @XmlElement(required = true)
    protected Drp drp;
    protected Pr pr;
    @XmlElement(name = "pr_alt")
    protected PrAlt prAlt;
    @XmlElement(name = "pr_ipa")
    protected PrIpa prIpa;
    @XmlElement(name = "pr_wod")
    protected PrWod prWod;
    protected Sound sound;
    protected Vr vr;
    protected List<Et> et;
    @XmlElement(required = true)
    protected Def def;

    /**
     * Gets the value of the drp property.
     * 
     * @return
     *     possible object is
     *     {@link Drp }
     *     
     */
    public Drp getDrp() {
        return drp;
    }

    /**
     * Sets the value of the drp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drp }
     *     
     */
    public void setDrp(Drp value) {
        this.drp = value;
    }

    /**
     * Gets the value of the pr property.
     * 
     * @return
     *     possible object is
     *     {@link Pr }
     *     
     */
    public Pr getPr() {
        return pr;
    }

    /**
     * Sets the value of the pr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pr }
     *     
     */
    public void setPr(Pr value) {
        this.pr = value;
    }

    /**
     * Gets the value of the prAlt property.
     * 
     * @return
     *     possible object is
     *     {@link PrAlt }
     *     
     */
    public PrAlt getPrAlt() {
        return prAlt;
    }

    /**
     * Sets the value of the prAlt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrAlt }
     *     
     */
    public void setPrAlt(PrAlt value) {
        this.prAlt = value;
    }

    /**
     * Gets the value of the prIpa property.
     * 
     * @return
     *     possible object is
     *     {@link PrIpa }
     *     
     */
    public PrIpa getPrIpa() {
        return prIpa;
    }

    /**
     * Sets the value of the prIpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrIpa }
     *     
     */
    public void setPrIpa(PrIpa value) {
        this.prIpa = value;
    }

    /**
     * Gets the value of the prWod property.
     * 
     * @return
     *     possible object is
     *     {@link PrWod }
     *     
     */
    public PrWod getPrWod() {
        return prWod;
    }

    /**
     * Sets the value of the prWod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrWod }
     *     
     */
    public void setPrWod(PrWod value) {
        this.prWod = value;
    }

    /**
     * Gets the value of the sound property.
     * 
     * @return
     *     possible object is
     *     {@link Sound }
     *     
     */
    public Sound getSound() {
        return sound;
    }

    /**
     * Sets the value of the sound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sound }
     *     
     */
    public void setSound(Sound value) {
        this.sound = value;
    }

    /**
     * Gets the value of the vr property.
     * 
     * @return
     *     possible object is
     *     {@link Vr }
     *     
     */
    public Vr getVr() {
        return vr;
    }

    /**
     * Sets the value of the vr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vr }
     *     
     */
    public void setVr(Vr value) {
        this.vr = value;
    }

    /**
     * Gets the value of the et property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the et property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Et }
     * 
     * 
     */
    public List<Et> getEt() {
        if (et == null) {
            et = new ArrayList<Et>();
        }
        return this.et;
    }

    /**
     * Gets the value of the def property.
     * 
     * @return
     *     possible object is
     *     {@link Def }
     *     
     */
    public Def getDef() {
        return def;
    }

    /**
     * Sets the value of the def property.
     * 
     * @param value
     *     allowed object is
     *     {@link Def }
     *     
     */
    public void setDef(Def value) {
        this.def = value;
    }

}
