//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.09 at 04:52:08 PM IST 
//


package x.y.jaxb;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}subj" minOccurs="0"/>
 *             &lt;element ref="{}art" minOccurs="0"/>
 *             &lt;element ref="{}formula" minOccurs="0"/>
 *             &lt;element ref="{}table" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{}hw"/>
 *           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *             &lt;element ref="{}pr" minOccurs="0"/>
 *             &lt;element ref="{}pr_alt" minOccurs="0"/>
 *             &lt;element ref="{}pr_ipa" minOccurs="0"/>
 *             &lt;element ref="{}pr_wod" minOccurs="0"/>
 *             &lt;element ref="{}sound" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *             &lt;element ref="{}ahw"/>
 *             &lt;sequence minOccurs="0">
 *               &lt;element ref="{}pr"/>
 *               &lt;element ref="{}pr_alt" minOccurs="0"/>
 *               &lt;element ref="{}pr_ipa" minOccurs="0"/>
 *               &lt;element ref="{}pr_wod" minOccurs="0"/>
 *               &lt;element ref="{}sound" minOccurs="0"/>
 *             &lt;/sequence>
 *           &lt;/sequence>
 *           &lt;element ref="{}vr" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}fl" minOccurs="0"/>
 *           &lt;element ref="{}in" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}lb" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *             &lt;sequence>
 *               &lt;element ref="{}cx"/>
 *               &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                 &lt;element ref="{}ss"/>
 *                 &lt;element ref="{}us"/>
 *               &lt;/choice>
 *             &lt;/sequence>
 *             &lt;element ref="{}et"/>
 *           &lt;/choice>
 *           &lt;element ref="{}sl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}dx"/>
 *           &lt;element ref="{}def"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}list" minOccurs="0"/>
 *           &lt;sequence>
 *             &lt;element ref="{}uro" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{}dro" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;choice maxOccurs="unbounded" minOccurs="0">
 *               &lt;sequence>
 *                 &lt;element ref="{}pl"/>
 *                 &lt;element ref="{}pt"/>
 *                 &lt;element ref="{}sa" minOccurs="0"/>
 *               &lt;/sequence>
 *               &lt;choice>
 *                 &lt;element ref="{}note"/>
 *               &lt;/choice>
 *               &lt;element ref="{}quote" maxOccurs="unbounded"/>
 *             &lt;/choice>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="printing" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="rating" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subj",
    "art",
    "formula",
    "table",
    "hw",
    "prAndPrAltAndPrIpa",
    "ahwAndPrAndPrAlt",
    "vr",
    "fl",
    "in",
    "lb",
    "cxAndSsOrUs",
    "sl",
    "dxOrDef",
    "list",
    "uro",
    "dro",
    "plAndPtAndSa"
})
@XmlRootElement(name = "entry")
public class Entry {

    protected Subj subj;
    protected Art art;
    protected Formula formula;
    protected Table table;
    @XmlElement(required = true)
    protected Hw hw;
    @XmlElements({
        @XmlElement(name = "pr", type = Pr.class),
        @XmlElement(name = "pr_alt", type = PrAlt.class),
        @XmlElement(name = "pr_ipa", type = PrIpa.class),
        @XmlElement(name = "pr_wod", type = PrWod.class),
        @XmlElement(name = "sound", type = Sound.class)
    })
    protected java.util.List<Object> prAndPrAltAndPrIpa;
    @XmlElements({
        @XmlElement(name = "ahw", type = Ahw.class),
        @XmlElement(name = "pr", type = Pr.class),
        @XmlElement(name = "pr_alt", type = PrAlt.class),
        @XmlElement(name = "pr_ipa", type = PrIpa.class),
        @XmlElement(name = "pr_wod", type = PrWod.class),
        @XmlElement(name = "sound", type = Sound.class)
    })
    protected java.util.List<Object> ahwAndPrAndPrAlt;
    protected Vr vr;
    protected Fl fl;
    protected java.util.List<In> in;
    protected java.util.List<Lb> lb;
    @XmlElements({
        @XmlElement(name = "cx", type = Cx.class),
        @XmlElement(name = "ss", type = Ss.class),
        @XmlElement(name = "us", type = Us.class),
        @XmlElement(name = "et", type = Et.class)
    })
    protected java.util.List<Object> cxAndSsOrUs;
    protected java.util.List<Sl> sl;
    @XmlElements({
        @XmlElement(name = "dx", type = Dx.class),
        @XmlElement(name = "def", type = Def.class)
    })
    protected java.util.List<Object> dxOrDef;
    protected x.y.jaxb.List list;
    protected java.util.List<Uro> uro;
    protected java.util.List<Dro> dro;
    @XmlElements({
        @XmlElement(name = "pl", type = Pl.class),
        @XmlElement(name = "pt", type = Pt.class),
        @XmlElement(name = "sa", type = Sa.class),
        @XmlElement(name = "note", type = Note.class),
        @XmlElement(name = "quote", type = Quote.class)
    })
    protected java.util.List<Object> plAndPtAndSa;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "printing")
    @XmlSchemaType(name = "anySimpleType")
    protected String printing;
    @XmlAttribute(name = "rating")
    @XmlSchemaType(name = "anySimpleType")
    protected String rating;

    /**
     * Gets the value of the subj property.
     * 
     * @return
     *     possible object is
     *     {@link Subj }
     *     
     */
    public Subj getSubj() {
        return subj;
    }

    /**
     * Sets the value of the subj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subj }
     *     
     */
    public void setSubj(Subj value) {
        this.subj = value;
    }

    /**
     * Gets the value of the art property.
     * 
     * @return
     *     possible object is
     *     {@link Art }
     *     
     */
    public Art getArt() {
        return art;
    }

    /**
     * Sets the value of the art property.
     * 
     * @param value
     *     allowed object is
     *     {@link Art }
     *     
     */
    public void setArt(Art value) {
        this.art = value;
    }

    /**
     * Gets the value of the formula property.
     * 
     * @return
     *     possible object is
     *     {@link Formula }
     *     
     */
    public Formula getFormula() {
        return formula;
    }

    /**
     * Sets the value of the formula property.
     * 
     * @param value
     *     allowed object is
     *     {@link Formula }
     *     
     */
    public void setFormula(Formula value) {
        this.formula = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link Table }
     *     
     */
    public Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link Table }
     *     
     */
    public void setTable(Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the hw property.
     * 
     * @return
     *     possible object is
     *     {@link Hw }
     *     
     */
    public Hw getHw() {
        return hw;
    }

    /**
     * Sets the value of the hw property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hw }
     *     
     */
    public void setHw(Hw value) {
        this.hw = value;
    }

    /**
     * Gets the value of the prAndPrAltAndPrIpa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prAndPrAltAndPrIpa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrAndPrAltAndPrIpa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pr }
     * {@link PrAlt }
     * {@link PrIpa }
     * {@link PrWod }
     * {@link Sound }
     * 
     * 
     */
    public java.util.List<Object> getPrAndPrAltAndPrIpa() {
        if (prAndPrAltAndPrIpa == null) {
            prAndPrAltAndPrIpa = new ArrayList<Object>();
        }
        return this.prAndPrAltAndPrIpa;
    }

    /**
     * Gets the value of the ahwAndPrAndPrAlt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ahwAndPrAndPrAlt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAhwAndPrAndPrAlt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ahw }
     * {@link Pr }
     * {@link PrAlt }
     * {@link PrIpa }
     * {@link PrWod }
     * {@link Sound }
     * 
     * 
     */
    public java.util.List<Object> getAhwAndPrAndPrAlt() {
        if (ahwAndPrAndPrAlt == null) {
            ahwAndPrAndPrAlt = new ArrayList<Object>();
        }
        return this.ahwAndPrAndPrAlt;
    }

    /**
     * Gets the value of the vr property.
     * 
     * @return
     *     possible object is
     *     {@link Vr }
     *     
     */
    public Vr getVr() {
        return vr;
    }

    /**
     * Sets the value of the vr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vr }
     *     
     */
    public void setVr(Vr value) {
        this.vr = value;
    }

    /**
     * Gets the value of the fl property.
     * 
     * @return
     *     possible object is
     *     {@link Fl }
     *     
     */
    public Fl getFl() {
        return fl;
    }

    /**
     * Sets the value of the fl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fl }
     *     
     */
    public void setFl(Fl value) {
        this.fl = value;
    }

    /**
     * Gets the value of the in property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the in property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link In }
     * 
     * 
     */
    public java.util.List<In> getIn() {
        if (in == null) {
            in = new ArrayList<In>();
        }
        return this.in;
    }

    /**
     * Gets the value of the lb property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lb property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLb().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lb }
     * 
     * 
     */
    public java.util.List<Lb> getLb() {
        if (lb == null) {
            lb = new ArrayList<Lb>();
        }
        return this.lb;
    }

    /**
     * Gets the value of the cxAndSsOrUs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cxAndSsOrUs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCxAndSsOrUs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cx }
     * {@link Ss }
     * {@link Us }
     * {@link Et }
     * 
     * 
     */
    public java.util.List<Object> getCxAndSsOrUs() {
        if (cxAndSsOrUs == null) {
            cxAndSsOrUs = new ArrayList<Object>();
        }
        return this.cxAndSsOrUs;
    }

    /**
     * Gets the value of the sl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sl }
     * 
     * 
     */
    public java.util.List<Sl> getSl() {
        if (sl == null) {
            sl = new ArrayList<Sl>();
        }
        return this.sl;
    }

    /**
     * Gets the value of the dxOrDef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dxOrDef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDxOrDef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dx }
     * {@link Def }
     * 
     * 
     */
    public java.util.List<Object> getDxOrDef() {
        if (dxOrDef == null) {
            dxOrDef = new ArrayList<Object>();
        }
        return this.dxOrDef;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link x.y.jaxb.List }
     *     
     */
    public x.y.jaxb.List getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link x.y.jaxb.List }
     *     
     */
    public void setList(x.y.jaxb.List value) {
        this.list = value;
    }

    /**
     * Gets the value of the uro property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uro property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUro().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Uro }
     * 
     * 
     */
    public java.util.List<Uro> getUro() {
        if (uro == null) {
            uro = new ArrayList<Uro>();
        }
        return this.uro;
    }

    /**
     * Gets the value of the dro property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dro property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDro().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dro }
     * 
     * 
     */
    public java.util.List<Dro> getDro() {
        if (dro == null) {
            dro = new ArrayList<Dro>();
        }
        return this.dro;
    }

    /**
     * Gets the value of the plAndPtAndSa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plAndPtAndSa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlAndPtAndSa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pl }
     * {@link Pt }
     * {@link Sa }
     * {@link Note }
     * {@link Quote }
     * 
     * 
     */
    public java.util.List<Object> getPlAndPtAndSa() {
        if (plAndPtAndSa == null) {
            plAndPtAndSa = new ArrayList<Object>();
        }
        return this.plAndPtAndSa;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the printing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrinting() {
        return printing;
    }

    /**
     * Sets the value of the printing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrinting(String value) {
        this.printing = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRating(String value) {
        this.rating = value;
    }

}
