//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.09 at 04:52:08 PM IST 
//


package x.y.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the x.y.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: x.y.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DLink }
     * 
     */
    public DLink createDLink() {
        return new DLink();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link It }
     * 
     */
    public It createIt() {
        return new It();
    }

    /**
     * Create an instance of {@link Inf }
     * 
     */
    public Inf createInf() {
        return new Inf();
    }

    /**
     * Create an instance of {@link Rom }
     * 
     */
    public Rom createRom() {
        return new Rom();
    }

    /**
     * Create an instance of {@link Ca }
     * 
     */
    public Ca createCa() {
        return new Ca();
    }

    /**
     * Create an instance of {@link Cat }
     * 
     */
    public Cat createCat() {
        return new Cat();
    }

    /**
     * Create an instance of {@link Pr }
     * 
     */
    public Pr createPr() {
        return new Pr();
    }

    /**
     * Create an instance of {@link Sc }
     * 
     */
    public Sc createSc() {
        return new Sc();
    }

    /**
     * Create an instance of {@link PrAlt }
     * 
     */
    public PrAlt createPrAlt() {
        return new PrAlt();
    }

    /**
     * Create an instance of {@link PrIpa }
     * 
     */
    public PrIpa createPrIpa() {
        return new PrIpa();
    }

    /**
     * Create an instance of {@link PrWod }
     * 
     */
    public PrWod createPrWod() {
        return new PrWod();
    }

    /**
     * Create an instance of {@link Sound }
     * 
     */
    public Sound createSound() {
        return new Sound();
    }

    /**
     * Create an instance of {@link Qword }
     * 
     */
    public Qword createQword() {
        return new Qword();
    }

    /**
     * Create an instance of {@link Ssl }
     * 
     */
    public Ssl createSsl() {
        return new Ssl();
    }

    /**
     * Create an instance of {@link SpIpa }
     * 
     */
    public SpIpa createSpIpa() {
        return new SpIpa();
    }

    /**
     * Create an instance of {@link Artref }
     * 
     */
    public Artref createArtref() {
        return new Artref();
    }

    /**
     * Create an instance of {@link Dxt }
     * 
     */
    public Dxt createDxt() {
        return new Dxt();
    }

    /**
     * Create an instance of {@link Dxn }
     * 
     */
    public Dxn createDxn() {
        return new Dxn();
    }

    /**
     * Create an instance of {@link Fl }
     * 
     */
    public Fl createFl() {
        return new Fl();
    }

    /**
     * Create an instance of {@link Spl }
     * 
     */
    public Spl createSpl() {
        return new Spl();
    }

    /**
     * Create an instance of {@link DxDef }
     * 
     */
    public DxDef createDxDef() {
        return new DxDef();
    }

    /**
     * Create an instance of {@link Ss }
     * 
     */
    public Ss createSs() {
        return new Ss();
    }

    /**
     * Create an instance of {@link Slb }
     * 
     */
    public Slb createSlb() {
        return new Slb();
    }

    /**
     * Create an instance of {@link Sx }
     * 
     */
    public Sx createSx() {
        return new Sx();
    }

    /**
     * Create an instance of {@link Sxn }
     * 
     */
    public Sxn createSxn() {
        return new Sxn();
    }

    /**
     * Create an instance of {@link Sl }
     * 
     */
    public Sl createSl() {
        return new Sl();
    }

    /**
     * Create an instance of {@link Ctn }
     * 
     */
    public Ctn createCtn() {
        return new Ctn();
    }

    /**
     * Create an instance of {@link Sn }
     * 
     */
    public Sn createSn() {
        return new Sn();
    }

    /**
     * Create an instance of {@link Snp }
     * 
     */
    public Snp createSnp() {
        return new Snp();
    }

    /**
     * Create an instance of {@link Sp }
     * 
     */
    public Sp createSp() {
        return new Sp();
    }

    /**
     * Create an instance of {@link Art }
     * 
     */
    public Art createArt() {
        return new Art();
    }

    /**
     * Create an instance of {@link Capt }
     * 
     */
    public Capt createCapt() {
        return new Capt();
    }

    /**
     * Create an instance of {@link Dim }
     * 
     */
    public Dim createDim() {
        return new Dim();
    }

    /**
     * Create an instance of {@link Sd }
     * 
     */
    public Sd createSd() {
        return new Sd();
    }

    /**
     * Create an instance of {@link Ure }
     * 
     */
    public Ure createUre() {
        return new Ure();
    }

    /**
     * Create an instance of {@link Cx }
     * 
     */
    public Cx createCx() {
        return new Cx();
    }

    /**
     * Create an instance of {@link Cl }
     * 
     */
    public Cl createCl() {
        return new Cl();
    }

    /**
     * Create an instance of {@link Ct }
     * 
     */
    public Ct createCt() {
        return new Ct();
    }

    /**
     * Create an instance of {@link Sense }
     * 
     */
    public Sense createSense() {
        return new Sense();
    }

    /**
     * Create an instance of {@link SpAlt }
     * 
     */
    public SpAlt createSpAlt() {
        return new SpAlt();
    }

    /**
     * Create an instance of {@link SpWod }
     * 
     */
    public SpWod createSpWod() {
        return new SpWod();
    }

    /**
     * Create an instance of {@link Svr }
     * 
     */
    public Svr createSvr() {
        return new Svr();
    }

    /**
     * Create an instance of {@link Vl }
     * 
     */
    public Vl createVl() {
        return new Vl();
    }

    /**
     * Create an instance of {@link Va }
     * 
     */
    public Va createVa() {
        return new Va();
    }

    /**
     * Create an instance of {@link Vpl }
     * 
     */
    public Vpl createVpl() {
        return new Vpl();
    }

    /**
     * Create an instance of {@link Sin }
     * 
     */
    public Sin createSin() {
        return new Sin();
    }

    /**
     * Create an instance of {@link Il }
     * 
     */
    public Il createIl() {
        return new Il();
    }

    /**
     * Create an instance of {@link If }
     * 
     */
    public If createIf() {
        return new If();
    }

    /**
     * Create an instance of {@link Set }
     * 
     */
    public Set createSet() {
        return new Set();
    }

    /**
     * Create an instance of {@link Ma }
     * 
     */
    public Ma createMa() {
        return new Ma();
    }

    /**
     * Create an instance of {@link Dt }
     * 
     */
    public Dt createDt() {
        return new Dt();
    }

    /**
     * Create an instance of {@link Dx }
     * 
     */
    public Dx createDx() {
        return new Dx();
    }

    /**
     * Create an instance of {@link Vi }
     * 
     */
    public Vi createVi() {
        return new Vi();
    }

    /**
     * Create an instance of {@link Aq }
     * 
     */
    public Aq createAq() {
        return new Aq();
    }

    /**
     * Create an instance of {@link Aqdate }
     * 
     */
    public Aqdate createAqdate() {
        return new Aqdate();
    }

    /**
     * Create an instance of {@link Un }
     * 
     */
    public Un createUn() {
        return new Un();
    }

    /**
     * Create an instance of {@link Math }
     * 
     */
    public Math createMath() {
        return new Math();
    }

    /**
     * Create an instance of {@link ILink }
     * 
     */
    public ILink createILink() {
        return new ILink();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Uro }
     * 
     */
    public Uro createUro() {
        return new Uro();
    }

    /**
     * Create an instance of {@link Vr }
     * 
     */
    public Vr createVr() {
        return new Vr();
    }

    /**
     * Create an instance of {@link Lb }
     * 
     */
    public Lb createLb() {
        return new Lb();
    }

    /**
     * Create an instance of {@link Sa }
     * 
     */
    public Sa createSa() {
        return new Sa();
    }

    /**
     * Create an instance of {@link Pl }
     * 
     */
    public Pl createPl() {
        return new Pl();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Hw }
     * 
     */
    public Hw createHw() {
        return new Hw();
    }

    /**
     * Create an instance of {@link Ahw }
     * 
     */
    public Ahw createAhw() {
        return new Ahw();
    }

    /**
     * Create an instance of {@link Vt }
     * 
     */
    public Vt createVt() {
        return new Vt();
    }

    /**
     * Create an instance of {@link DxEty }
     * 
     */
    public DxEty createDxEty() {
        return new DxEty();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Subj }
     * 
     */
    public Subj createSubj() {
        return new Subj();
    }

    /**
     * Create an instance of {@link Def }
     * 
     */
    public Def createDef() {
        return new Def();
    }

    /**
     * Create an instance of {@link Us }
     * 
     */
    public Us createUs() {
        return new Us();
    }

    /**
     * Create an instance of {@link Quote }
     * 
     */
    public Quote createQuote() {
        return new Quote();
    }

    /**
     * Create an instance of {@link Alpha }
     * 
     */
    public Alpha createAlpha() {
        return new Alpha();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Formula }
     * 
     */
    public Formula createFormula() {
        return new Formula();
    }

    /**
     * Create an instance of {@link In }
     * 
     */
    public In createIn() {
        return new In();
    }

    /**
     * Create an instance of {@link Et }
     * 
     */
    public Et createEt() {
        return new Et();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Dro }
     * 
     */
    public Dro createDro() {
        return new Dro();
    }

    /**
     * Create an instance of {@link Drp }
     * 
     */
    public Drp createDrp() {
        return new Drp();
    }

    /**
     * Create an instance of {@link Pt }
     * 
     */
    public Pt createPt() {
        return new Pt();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

}
