//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.09 at 04:52:08 PM IST 
//


package x.y.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}sn" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}sp"/>
 *           &lt;element ref="{}sp_alt" minOccurs="0"/>
 *           &lt;element ref="{}sp_ipa" minOccurs="0"/>
 *           &lt;element ref="{}sp_wod" minOccurs="0"/>
 *           &lt;element ref="{}sound" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}svr" minOccurs="0"/>
 *         &lt;element ref="{}sin" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}slb" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}set" minOccurs="0"/>
 *         &lt;element ref="{}ssl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}dt" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}sd"/>
 *           &lt;element ref="{}sin" minOccurs="0"/>
 *           &lt;sequence minOccurs="0">
 *             &lt;element ref="{}sp"/>
 *             &lt;element ref="{}sp_alt" minOccurs="0"/>
 *             &lt;element ref="{}sp_ipa" minOccurs="0"/>
 *             &lt;element ref="{}sp_wod" minOccurs="0"/>
 *             &lt;element ref="{}sound" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{}slb" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}ssl" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}dt" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="snumb" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "sense")
public class Sense {

    @XmlElementRefs({
        @XmlElementRef(name = "sound", type = Sound.class),
        @XmlElementRef(name = "sd", type = Sd.class),
        @XmlElementRef(name = "ssl", type = Ssl.class),
        @XmlElementRef(name = "sp_wod", type = SpWod.class),
        @XmlElementRef(name = "dt", type = Dt.class),
        @XmlElementRef(name = "sin", type = Sin.class),
        @XmlElementRef(name = "slb", type = Slb.class),
        @XmlElementRef(name = "set", type = Set.class),
        @XmlElementRef(name = "sp", type = Sp.class),
        @XmlElementRef(name = "sp_alt", type = SpAlt.class),
        @XmlElementRef(name = "sp_ipa", type = SpIpa.class),
        @XmlElementRef(name = "svr", type = Svr.class),
        @XmlElementRef(name = "sn", type = Sn.class)
    })
    protected List<Object> content;
    @XmlAttribute(name = "snumb")
    @XmlSchemaType(name = "anySimpleType")
    protected String snumb;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Sin" is used by two different parts of a schema. See: 
     * line 136 of file:/C:/Satish/SVN/Workspaces/Idea/Ripple/src/xml/collegiate.xsd
     * line 129 of file:/C:/Satish/SVN/Workspaces/Idea/Ripple/src/xml/collegiate.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sound }
     * {@link Sd }
     * {@link Ssl }
     * {@link SpWod }
     * {@link Dt }
     * {@link Sin }
     * {@link Slb }
     * {@link Set }
     * {@link Sp }
     * {@link SpAlt }
     * {@link SpIpa }
     * {@link Svr }
     * {@link Sn }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the snumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnumb() {
        return snumb;
    }

    /**
     * Sets the value of the snumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnumb(String value) {
        this.snumb = value;
    }

}
