//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.09 at 04:52:08 PM IST 
//


package x.y.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ure"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}pr"/>
 *           &lt;element ref="{}pr_alt" minOccurs="0"/>
 *           &lt;element ref="{}pr_ipa" minOccurs="0"/>
 *           &lt;element ref="{}pr_wod" minOccurs="0"/>
 *           &lt;element ref="{}sound" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}vr" minOccurs="0"/>
 *         &lt;element ref="{}fl" minOccurs="0"/>
 *         &lt;element ref="{}lb" minOccurs="0"/>
 *         &lt;element ref="{}sl" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ure",
    "pr",
    "prAlt",
    "prIpa",
    "prWod",
    "sound",
    "vr",
    "fl",
    "lb",
    "sl"
})
@XmlRootElement(name = "uro")
public class Uro {

    @XmlElement(required = true)
    protected Ure ure;
    protected Pr pr;
    @XmlElement(name = "pr_alt")
    protected PrAlt prAlt;
    @XmlElement(name = "pr_ipa")
    protected PrIpa prIpa;
    @XmlElement(name = "pr_wod")
    protected PrWod prWod;
    protected Sound sound;
    protected Vr vr;
    protected Fl fl;
    protected Lb lb;
    protected Sl sl;

    /**
     * Gets the value of the ure property.
     * 
     * @return
     *     possible object is
     *     {@link Ure }
     *     
     */
    public Ure getUre() {
        return ure;
    }

    /**
     * Sets the value of the ure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ure }
     *     
     */
    public void setUre(Ure value) {
        this.ure = value;
    }

    /**
     * Gets the value of the pr property.
     * 
     * @return
     *     possible object is
     *     {@link Pr }
     *     
     */
    public Pr getPr() {
        return pr;
    }

    /**
     * Sets the value of the pr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pr }
     *     
     */
    public void setPr(Pr value) {
        this.pr = value;
    }

    /**
     * Gets the value of the prAlt property.
     * 
     * @return
     *     possible object is
     *     {@link PrAlt }
     *     
     */
    public PrAlt getPrAlt() {
        return prAlt;
    }

    /**
     * Sets the value of the prAlt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrAlt }
     *     
     */
    public void setPrAlt(PrAlt value) {
        this.prAlt = value;
    }

    /**
     * Gets the value of the prIpa property.
     * 
     * @return
     *     possible object is
     *     {@link PrIpa }
     *     
     */
    public PrIpa getPrIpa() {
        return prIpa;
    }

    /**
     * Sets the value of the prIpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrIpa }
     *     
     */
    public void setPrIpa(PrIpa value) {
        this.prIpa = value;
    }

    /**
     * Gets the value of the prWod property.
     * 
     * @return
     *     possible object is
     *     {@link PrWod }
     *     
     */
    public PrWod getPrWod() {
        return prWod;
    }

    /**
     * Sets the value of the prWod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrWod }
     *     
     */
    public void setPrWod(PrWod value) {
        this.prWod = value;
    }

    /**
     * Gets the value of the sound property.
     * 
     * @return
     *     possible object is
     *     {@link Sound }
     *     
     */
    public Sound getSound() {
        return sound;
    }

    /**
     * Sets the value of the sound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sound }
     *     
     */
    public void setSound(Sound value) {
        this.sound = value;
    }

    /**
     * Gets the value of the vr property.
     * 
     * @return
     *     possible object is
     *     {@link Vr }
     *     
     */
    public Vr getVr() {
        return vr;
    }

    /**
     * Sets the value of the vr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vr }
     *     
     */
    public void setVr(Vr value) {
        this.vr = value;
    }

    /**
     * Gets the value of the fl property.
     * 
     * @return
     *     possible object is
     *     {@link Fl }
     *     
     */
    public Fl getFl() {
        return fl;
    }

    /**
     * Sets the value of the fl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fl }
     *     
     */
    public void setFl(Fl value) {
        this.fl = value;
    }

    /**
     * Gets the value of the lb property.
     * 
     * @return
     *     possible object is
     *     {@link Lb }
     *     
     */
    public Lb getLb() {
        return lb;
    }

    /**
     * Sets the value of the lb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lb }
     *     
     */
    public void setLb(Lb value) {
        this.lb = value;
    }

    /**
     * Gets the value of the sl property.
     * 
     * @return
     *     possible object is
     *     {@link Sl }
     *     
     */
    public Sl getSl() {
        return sl;
    }

    /**
     * Sets the value of the sl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sl }
     *     
     */
    public void setSl(Sl value) {
        this.sl = value;
    }

}
